feat: integrate trino
bzkf/onco-analytics-on-fhir pull request #202
Opened 2024-09-04 13:14 UTC by jasminziegler

2024-09-04 13:43 UTC, pcvolkmer commented on docker-compose/compose.pathling.yaml
> +        -Djavax.jdo.option.ConnectionUserName=hive
Use var from .env

2024-09-04 13:50 UTC, pcvolkmer commented on docker-compose/compose.pathling.yaml
> +        -Djavax.jdo.option.ConnectionUserName=hive
```suggestion
        -Djavax.jdo.option.ConnectionUserName=${HIVE_METASTORE_USERNAME}
```

2024-09-04 13:50 UTC, pcvolkmer commented on docker-compose/compose.pathling.yaml
> +      AWS_ACCESS_KEY_ID: "admin"
```suggestion
        -Djavax.jdo.option.ConnectionPassword=${HIVE_METASTORE_PASSWORD}
```

2024-09-04 13:52 UTC, pcvolkmer commented on docker-compose/compose.pathling.yaml
> +        -Djavax.jdo.option.ConnectionPassword=hive
```suggestion
        -Djavax.jdo.option.ConnectionPassword=${HIVE_METASTORE_PASSWORD}
```

2024-09-08 15:08 UTC, jasminziegler commented
ich krieg das mit tsqllint in vscode irgendwie nicht hin, das plugin crashed immer wieder. ideas anyone?

2024-09-08 17:06 UTC, pcvolkmer reviewed
fix: use uppercase keywords to make tsqllinter happy

2024-09-08 17:06 UTC, pcvolkmer commented on src/trino/queries/counts_cancer_diagnoses_2018-2023.sql
> +                        ) AS varbinary
```suggestion
                        ) AS VARBINARY
```

2024-09-08 17:06 UTC, pcvolkmer commented on src/trino/queries/counts_cancer_diagnoses_2018-2023.sql
> +                        ) AS varbinary
```suggestion
                        ) AS VARBINARY
```

2024-09-08 17:06 UTC, pcvolkmer commented on src/trino/queries/counts_cancer_diagnoses_2018-2023.sql
> +                        ) AS varbinary
```suggestion
                        ) AS VARBINARY
```

2024-09-08 17:06 UTC, pcvolkmer commented on src/trino/queries/counts_cancer_diagnoses_2018-2023.sql
> +        CAST(date_diagnosis_year AS INTEGER) as "Year of Diagnosis",
```suggestion
        CAST(date_diagnosis_year AS INTEGER) AS "Year of Diagnosis",
```

2024-09-08 17:06 UTC, pcvolkmer commented on src/trino/queries/counts_cancer_diagnoses_by_icd10code_2022.sql
> +                        ) AS varbinary
```suggestion
                        ) AS VARBINARY
```

2024-09-08 17:06 UTC, pcvolkmer commented on src/trino/queries/counts_cancer_diagnoses_by_icd10code_2022.sql
> +                        ) AS varbinary
```suggestion
                        ) AS VARBINARY
```

2024-09-08 17:06 UTC, pcvolkmer commented on src/trino/queries/counts_cancer_diagnoses_by_icd10code_2022.sql
> +                        ) AS varbinary
```suggestion
                        ) AS VARBINARY
```

2024-09-08 17:06 UTC, pcvolkmer commented on src/trino/queries/counts_cancer_diagnoses_by_icd10code_2022.sql
> +        CAST(date_diagnosis_year AS INTEGER) as "Year of Diagnosis",
```suggestion
        CAST(date_diagnosis_year AS INTEGER) AS "Year of Diagnosis",
```

2024-09-08 17:06 UTC, pcvolkmer commented on src/trino/queries/counts_deceased_patients_2018-2023.sql
> +    CAST(year(date(deceasedDateTime)) AS INTEGER) AS "Year of Death",
```suggestion
    CAST(YEAR(DATE(deceasedDateTime)) AS INTEGER) AS "Year of Death",
```

2024-09-08 17:06 UTC, pcvolkmer commented on src/trino/queries/counts_deceased_patients_2018-2023.sql
> +    year(date(deceasedDateTime))
```suggestion
    YEAR(DATE(deceasedDateTime))
```

2024-09-08 17:06 UTC, pcvolkmer commented on src/trino/queries/counts_deceased_patients_2018-2023.sql
> +    year(date(deceasedDateTime)) BETWEEN 2018
```suggestion
    YEAR(DATE(deceasedDateTime)) BETWEEN 2018
```

2024-09-08 17:06 UTC, pcvolkmer commented on src/trino/queries/counts_deceased_patients_2018-2023.sql
> +    year(date(deceasedDateTime))
```suggestion
    YEAR(DATE(deceasedDateTime))
```

2024-09-08 17:15 UTC, pcvolkmer commented
Bezüglich der TSQLLint-Meldungen für 2510c3f mit  "Expected: Set ...." bitte beachten:

https://learn.microsoft.com/en-us/sql/t-sql/statements/set-ansi-nulls-transact-sql?view=sql-server-ver16#remarks
https://learn.microsoft.com/en-us/sql/t-sql/statements/set-nocount-transact-sql?view=sql-server-ver16

2024-09-08 17:20 UTC, pcvolkmer reviewed
Added some settings to the top of the SQL files

2024-09-08 17:20 UTC, pcvolkmer commented on src/trino/queries/counts_cancer_diagnoses_2018-2023.sql
> +WITH fhir_data AS (
```suggestion
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET QUOTED_IDENTIFIER ON

WITH fhir_data AS (
```

2024-09-08 17:20 UTC, pcvolkmer commented on src/trino/queries/counts_cancer_diagnoses_by_icd10code_2022.sql
> +WITH fhir_data AS (
```suggestion
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET QUOTED_IDENTIFIER ON

WITH fhir_data AS (
```

2024-09-08 17:20 UTC, pcvolkmer commented on src/trino/queries/counts_deceased_patients_2018-2023.sql
> +WITH onkostar_data AS (
```suggestion
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET QUOTED_IDENTIFIER ON

WITH onkostar_data AS (
```

2024-09-08 17:23 UTC, pcvolkmer commented
> ich krieg das mit tsqllint in vscode irgendwie nicht hin, das plugin crashed immer wieder. ideas anyone?

Du kannst das Tool auch runter laden, entpacken und auf der Konsole ausführen: https://github.com/tsqllint/tsqllint/releases/tag/1.15.3

```bash
./TSQLLint *.sql
```

unter Windows ohne `./` vor dem Befehl.

Etwas umständlicher aber funktioniert.

2024-09-08 17:50 UTC, chgl commented
Ah, ich denke hier schlägt der tssqllinter falsch an - das ist ja Trino SQL, kein T-SQL. der tsqllint ist in der neuesten megalinter version auch deprecated, stattdessen gibt es dann sqlfluff das auch explizit den trino sql dialekt unterstützt. Ich mach mich mal dran den megalinter hier upzudaten. Bis dahin können die tsqllint beschwerden ignoriert werden, oder der linter erstmal deaktiviert werden.

2024-09-08 17:59 UTC, chgl requested changes

2024-09-08 17:59 UTC, chgl commented on docker-compose/.env
> +AWS_ACCESS_KEY_ID=admin
Ich würde vorschlagen nur einmal

```
AWS_ACCESS_KEY_ID=admin
AWS_SECRET_ACCESS_KEY=miniopass
```

zu definieren und dass dann überall im compose anstelle der pro-service variablen zu nutzen.

2024-09-08 17:59 UTC, chgl commented on docker-compose/compose.pathling.yaml
> +      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
```suggestion
      MINIO_ROOT_USER: "${AWS_ACCESS_KEY_ID}"
```

2024-09-08 17:59 UTC, chgl commented on docker-compose/compose.pathling.yaml
> +      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}" # gitleaks:allow
```suggestion
      MINIO_ROOT_PASSWORD: "${AWS_SECRET_ACCESS_KEY}" # gitleaks:allow
```

2024-09-08 17:59 UTC, chgl commented on docker-compose/compose.pathling.yaml
> +      fs.s3a.secret.key: "${S3A_SECRET_KEY}"
```suggestion
      fs.s3a.access.key: "${AWS_ACCESS_KEY_ID}"
      fs.s3a.secret.key: "${AWS_SECRET_ACCESS_KEY}"
```

2024-09-08 17:59 UTC, chgl commented on docker-compose/compose.pathling.yaml
> +      AWS_SECRET_ACCESS_KEY: "miniopass"
```suggestion
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
```

2024-09-08 17:59 UTC, chgl commented on docker-compose/compose.pathling.yaml
> +        -Djavax.jdo.option.ConnectionPassword=${HIVE_METASTORE_PASSWORD}
```suggestion
        -Djavax.jdo.option.ConnectionUserName=${POSTGRESQL_USERNAME}
        -Djavax.jdo.option.ConnectionPassword=${POSTGRESQL_PASSWORD}
```

2024-09-08 17:59 UTC, chgl commented on docker-compose/.env
> +HIVE_AWS_SECRET_ACCESS_KEY=miniopass
```suggestion

```

2024-09-08 17:59 UTC, chgl commented on docker-compose/compose.pathling.yaml
> +      FHIR_URL: http://fhir-server:8080/fhir
```suggestion
      FHIR_URL: http://pathling:8080/fhir
```

2024-09-08 17:59 UTC, chgl commented on docker-compose/compose.pathling.yaml
> +  import-resources:
wenn wir resourcen via fhir-to-pathling-server importieren brauchen wir diesen service nicht, warehousekeeper müsste an der stelle noch so konfiguriert sein, dass es erst nach dem abschluss des imports läufts.

2024-09-08 17:59 UTC, chgl commented on docker-compose/compose.trino.yaml
> +      AWS_SECRET_ACCESS_KEY: "miniopass"
```suggestion
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
```

2024-09-08 18:41 UTC, pcvolkmer reviewed
Remove obsolete ordering ignored later in Line 150ff

2024-09-08 18:41 UTC, pcvolkmer commented on src/trino/queries/counts_deceased_patients_2018-2023.sql
> +  ORDER BY
```suggestion
```

2024-09-08 18:41 UTC, pcvolkmer commented on src/trino/queries/counts_deceased_patients_2018-2023.sql
> +    year(date(deceasedDateTime))
```suggestion
```

2024-09-08 19:23 UTC, chgl commented
> Ah, ich denke hier schlägt der tssqllinter falsch an - das ist ja Trino SQL, kein T-SQL. der tsqllint ist in der neuesten megalinter version auch deprecated, stattdessen gibt es dann sqlfluff das auch explizit den trino sql dialekt unterstützt. Ich mach mich mal dran den megalinter hier upzudaten. Bis dahin können die tsqllint beschwerden ignoriert werden, oder der linter erstmal deaktiviert werden.

In master ist megalinter jetzt v8 ohne tssql, dafür mit sqlfluff.

2024-09-08 19:59 UTC, jasminziegler commented
> > Ah, ich denke hier schlägt der tssqllinter falsch an - das ist ja Trino SQL, kein T-SQL. der tsqllint ist in der neuesten megalinter version auch deprecated, stattdessen gibt es dann sqlfluff das auch explizit den trino sql dialekt unterstützt. Ich mach mich mal dran den megalinter hier upzudaten. Bis dahin können die tsqllint beschwerden ignoriert werden, oder der linter erstmal deaktiviert werden.
> 
> 
> 
> In master ist megalinter jetzt v8 ohne tssql, dafür mit sqlfluff.

Thanks dear colleague!

2024-09-09 12:13 UTC, jasminziegler commented on docker-compose/compose.pathling.yaml
> +  import-resources:
soll ich den import-resources service dann ganz löschen?

2024-09-26 09:40 UTC, jasminziegler commented
@chgl @pcvolkmer ich hab jetzt die .env Datei noch angepasst und die Queries nochmal aktualisiert, sodass wir die neue Berechnungsformel Abweichung zum Mittelwert verwenden wie zitiert. 
ein wichtiger Hinweis von Jonathan war noch folgender:

"[...] Oder (und das vermute/hoffe ich) ist das Repo/der Quellcode zu dem Setup einsehbar? Wenn ja, wo? Der Link sollte meines Erachtens noch bspw. als "Availability of data and materials: The repository for the setup is available on GitHub ([https://github.com/path/here](https://www.google.com/url?q=https://github.com/path/here&sa=D&source=docs&ust=1727344836464646&usg=AOvVaw16ELlw-E-mmvF4cCmJoz-0)). Extensive information about the usage and optional parameterization is available in the respective readme files in the repository." eingebaut werden."

was fehlt an dieser Stelle noch, um das Setup an anderen Standorten ausführbar zu machen? 
ein Readme kann ich dann gerne noch ergänzen

2024-10-08 09:44 UTC, closed without merging

2024-10-08 11:22 UTC, jasminziegler commented
Moved this to seperate repo for MIE2025.